import * as yup from 'yup';

export const optionChainAnalysisValidationSchema = yup.object().shape({
  strike_price: yup.number().required(),
  expiry_date: yup.date().required(),
  option_type: yup.string().nullable(),
  last_traded_price: yup.number().nullable(),
  volume_traded_today: yup.number().integer().nullable(),
  open_interest: yup.number().integer().nullable(),
  implied_volatility: yup.number().nullable(),
  change_in_open_interest: yup.number().integer().nullable(),
  previous_day_volume: yup.number().integer().nullable(),
  historical_volatility: yup.number().nullable(),
  delta: yup.number().nullable(),
  greeks: yup.string().nullable(),
  theta: yup.number().nullable(),
  vega: yup.number().nullable(),
  option_chain_timestamp: yup.date().required(),
  underlying_asset: yup.string().nullable(),
  option_chain_analysis: yup.string().nullable(),
  analysis_timestamp: yup.date().nullable(),
  option_chain_trend: yup.string().nullable(),
  option_chain_sentiment: yup.string().nullable(),
  analysis_summary: yup.string().nullable(),
  analysis_accuracy: yup.number().nullable(),
  analysis_confidence_interval: yup.number().nullable(),
  analysis_comments: yup.string().nullable(),
  analysis_update_frequency: yup.string().nullable(),
  option_chain_prediction: yup.number().nullable(),
});
